name: Rolling - Semi-Binary Build
# description: 'Build & test that compiles the main dependencies from source.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on main branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, '/refs/heads') }}

jobs:
  semi_binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy, kilted, rolling]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: testing
      upstream_workspace: topic_based_hardware_interfaces.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: main
  semi_binary_clang:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy, kilted, rolling]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: testing
      upstream_workspace: topic_based_hardware_interfaces.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: main
      additional_debs: clang
      c_compiler: clang
      cxx_compiler: clang++
      not_test_build: true
